language: cpp

compiler:
  - gcc

before_install:
  # We need this line to have g++4.9.2 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.9.2 g++-4.9.2
  # We want to compile with g++ 4.9.2 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9.2 90

script: make release
