language: generic
sudo: false
git:
  submodules: false
cache:
  apt: true

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libpthread-stubs0-dev
            - libgl1-mesa-dev
            - libx11-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libglew-dev
            - libjpeg8-dev
            - libsndfile1-dev
            - libopenal-dev
            - libudev-dev
            - libx11-xcb-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: &sources
            - r-packages-precise
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libpthread-stubs0-dev
            - libgl1-mesa-dev
            - libx11-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libglew-dev
            - libjpeg8-dev
            - libsndfile1-dev
            - libopenal-dev
            - libudev-dev
            - libx11-xcb-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: *sources

install:
  - cd ..
  - git clone --depth 1 https://github.com/SFML/SFML.git
  - cd SFML
  # build and install it
  - mkdir build && cd build
  - cmake -G"Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX:PATH="$HOME"
  - make install
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api-key:
    secure: T40df2pQsgo3oAmQxVqrz28g0nXVeTLlTnk7p5jrIwxcX8myRGe4C6OuE7qzECl7BAS6zRr/t8Gv7ytZQyZ0occHZctfybV7m+PXISavTpjwtVqjjYo0N9DT1lD3p5awDqnaPfRt657J0nvSp1gXThgdC5l1zrrnRK/L0HY43co=
  file: "release.tar.bz2"
  skip_cleanup: true
  on:
    tags: true

script:
  - make git
  - make release
