language: generic
sudo: false
cache:
  apt: true

matrix:
  include:
    - env: SFML_INSTALLDIR="$HOME" COMPILER_NAME="GCC 5" CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libpthread-stubs0-dev
            - libgl1-mesa-dev
            - libx11-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libglew-dev
            - libjpeg8-dev
            - libsndfile1-dev
            - libopenal-dev
            - libudev-dev
            - libx11-xcb-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: &sources
            - r-packages-precise
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - env: SFML_INSTALLDIR="$HOME" COMPILER_NAME="Clang 3.8" CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libpthread-stubs0-dev
            - libgl1-mesa-dev
            - libx11-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libglew-dev
            - libjpeg8-dev
            - libsndfile1-dev
            - libopenal-dev
            - libudev-dev
            - libx11-xcb-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: *sources

install:
  - cd ..
  - git clone --depth 100 https://github.com/SFML/SFML.git && cd SFML  # SFML tags every 15-50 commits, so we're safe on that front
  - export SFML_TAG=$(git describe --tags --abbrev=0)
  - git reset --hard $SFML_TAG
  - mkdir build && cd build
  - cmake -G"Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX:PATH="$SFML_INSTALLDIR"
  - make -j2 install
  - cd $TRAVIS_BUILD_DIR

script: make -j2

before_deploy:
  - mkdir release
  - cp -r out/Cwepper assets release/
  - LD_LIBRARY_PATH=~/lib ldd release/Cwepper | grep sfml | awk '{system("cp " $3 " release/")}'
  - tar -caf "$TRAVIS_TAG Ubuntu precise x86_64 $COMPILER_NAME.tbz2" release

deploy:
  provider: releases
  api-key:
    secure: DJWlmoC+DOS9s3nv+GpQiCbpbfqLwjU/ir5Ysi3AUwhcqteU+YFNjFxgqFZjpjGP9/qSAUVd4RWKzr4aVMJKDQTcfPocUkYGObyoAc5sxioLam75cySvJDj9y8L4OxquspX5rT5oO7VCiOU9zwZpRqlNFKCMbKvvacd5J5JC6lw=
  file: "$TRAVIS_TAG Ubuntu precise x86_64 $COMPILER_NAME.tbz2"
  skip_cleanup: true
  on:
    tags: true
